call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-streamline-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-cloudbeds-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-stayntouch-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-rns-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-booking_automation-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-lodgify-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-hostfully-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-guesty-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-clock-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-mews-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-rdp-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-direct-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-fantastic-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-vrm-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-myvr-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-igms-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-ciirus-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-escapia-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-ownerrez-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-hostaway-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-lynx_api-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-lynx_ui-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-automation_api-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder_property-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-realtime-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-guest_app-realtime-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-secondary_groups-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation-orchestrator-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-arrival_instruction-orchestrator-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-booking_confirmation-orchestrator-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-request_review-orchestrator-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-guidebook-orchestrator-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-offer_stay_extension-orchestrator-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-checkout-orchestrator-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-others-orchestrator-lambda
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-arrival_instruction-automation
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-booking_confirmation-automation
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-request_review-automation
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-guidebook-automation
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-offer_stay_extension-automation
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-checkout-automation
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-others-automation
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-processor-high_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-processor-medium_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-processor-low_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-group-processor-high_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-group-processor-medium_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-group-processor-low_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-streamline-processor-high_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-cloudbeds-processor-high_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-stayntouch-processor-high_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-ba-processor-high_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-lodgify-processor-high_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-hostfully-processor-high_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-guesty-processor-high_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-clock-processor-high_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-mews-processor-high_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-rdp-processor-high_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-direct-processor-high_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-fantastic-processor-high_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-vrm-processor-high_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-myvr-processor-high_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-igms-processor-high_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-ciirus-processor-high_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-escapia-processor-high_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-ownerrez-processor-high_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-hostaway-processor-high_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-streamline-processor-medium_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-cloudbeds-processor-medium_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-stayntouch-processor-medium_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-ba-processor-medium_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-lodgify-processor-medium_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-hostfully-processor-medium_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-guesty-processor-medium_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-clock-processor-medium_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-mews-processor-medium_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-rdp-processor-medium_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-direct-processor-medium_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-fantastic-processor-medium_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-vrm-processor-medium_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-myvr-processor-medium_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-igms-processor-medium_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-ciirus-processor-medium_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-escapia-processor-medium_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-ownerrez-processor-medium_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-hostaway-processor-medium_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-streamline-processor-low_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-cloudbeds-processor-low_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-stayntouch-processor-low_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-ba-processor-low_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-lodgify-processor-low_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-hostfully-processor-low_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-guesty-processor-low_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-clock-processor-low_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-mews-processor-low_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-rdp-processor-low_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-direct-processor-low_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-fantastic-processor-low_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-vrm-processor-low_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-myvr-processor-low_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-igms-processor-low_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-ciirus-processor-low_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-escapia-processor-low_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-ownerrez-processor-low_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-hostaway-processor-low_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-default-processor-high_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-default-processor-medium_priority
call aws lambda update-function-configuration --timeout 300 --region us-east-1 --query "[FunctionName,Timeout]"  --function-name prod-automation_feeder-default-processor-low_priority